[project]
name            = "pubg"
requires-python = ">=3.12"
version         = "0.1.0"

dependencies = [
    "pandas",
    "numpy",
    "pyarrow",
    "scikit-learn>=1.9.0",
    "lightgbm>=4.7.0",
    "pyyaml>=6.0.3",
    "mlflow>=3.15.2",
    "optuna>=4.9.0",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
]

[build-system]
requires        = ["setuptools"]
build-backend   = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest",
    "jupyterlab",
    "matplotlib",
    "seaborn",
    "ruff"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
